# Products

GET http://localhost:8082/products

###

GET http://localhost:8082/products/61f9b493d9273ce3177b3197

###

POST http://localhost:8082/products
Content-Type: application/json

{
    "id": 0,
    "name": "mickey mouse0",
    "price": 20,
    "quantity": 0,
    "img": "https:upload.wikimedia.org/wikipedia/he/0/07/Donald_Duck1.gif",
    "added": false,
    "message": ""
}

###

DELETE http://localhost:8082/products/61f9b308586fc2b0fa536299

###

PATCH http://localhost:8082/products/61f9b493d9273ce3177b3197
Content-Type: application/json

{
    "id": 2,
    "name": "mickey mouse 15",
    "price": 20,
    "quantity": 0,
    "img": "https:upload.wikimedia.org/wikipedia/he/0/07/Donald_Duck1.gif",
    "added": false,
    "message": ""
}
id added
###