# Products

GET http://localhost:8082/products

###

GET http://localhost:8082/products/61f9b493d9273ce3177b3197

###

POST http://localhost:8082/products
Content-Type: application/json

 {
    "id": "823",
    "name": "crazy cat",
    "price": "1200",
    "quantity": "1",
    "message": "good",
    "img": "https://i.pinimg.com/564x/a2/63/8a/a2638a9de0c207a6f7a90cabd8a5a594.jpg",
    "added": false
}

###

DELETE http://localhost:8082/products/62025784cf01ee9d6bb22cf6

###

PATCH http://localhost:8082/products/62026817b84284b8f95c6756
Content-Type: application/json

 {
    "id": "83",
    "name": "crazy catjhhkjhj",
    "price": "1200",
    "quantity": "1",
    "message": "good",
    "img": "https://i.pinimg.com/564x/a2/63/8a/a2638a9de0c207a6f7a90cabd8a5a594.jpg",
    "added": false
}

###