GET http://localhost:8082/users

###

POST http://localhost:8082/users
Content-Type: application/json

{
    "active": true,
    "email": "",
    "watchList": [],
    "cart":[]
}

###

DELETE http://localhost:8082/users/61fbe52dc123c92475c6bca5

###

PATCH http://localhost:8082/users/6200f4b9a55cc66314c74a1f
Content-Type: application/json

{
   {"product":""}
}

###
###
###

GET http://localhost:8082/users/cart


###

GET http://localhost:8082/users/cart/6203c530703bc5085dbb6b88

###

PATCH http://localhost:8082/users/cart/patch/push/6203c530703bc5085dbb6b88
Content-Type: application/json

 {
    "id": "87",
    "name": "big dog",
    "price": "187",
    "quantity": "1",
    "message": "good dog",
    "img": "https://i.pinimg.com/564x/a2/63/8a/a2638a9de0c207a6f7a90cabd8a5a594.jpg",
    "added": false
}

###

PATCH http://localhost:8082/users/cart/patch/pull/62022164022e7904e89fda6c
Content-Type: application/json


###
DELETE http://localhost:8082/users/cart/delete/6202c3734b99f72103547700
###

###
###
###

GET http://localhost:8082/users/watchList

###

GET http://localhost:8082/users/watchList/6203c530703bc5085dbb6b88

###

PATCH http://localhost:8082/users/watchList/patch/push/6203c530703bc5085dbb6b88
Content-Type: application/json

 {
    "name": "Lion king 1 (1994)",
    "img": "https://www.dvdplanetstore.pk/wp-content/uploads/2017/12/bKPtXn9n4M4s8vvZrbw40mYsefB.jpg",
    "trailerSrc": "https://www.youtube.com/embed/7pTs8v-fFw0",
    "time": "1:05",
    "added": false,
    "message": "",
    "movieSrc": "https://s2.sratim.video/movie/SD/480/5317.mp4?token=vVEaigUyvkepbVcIOvgZPQ&time=1643744587&uid=",
    "categories": "SelectedMovies"
}

###

PATCH http://localhost:8082/users/watchList/patch/pull/62022164022e7904e89fda6c
Content-Type: application/json


###
DELETE http://localhost:8082/users/watchList/delete/6202c3734b99f72103547700
###

