GET http://localhost:8082/users

###

POST http://localhost:8082/users
Content-Type: application/json

{
    "active": true,
    "email": "",
    "watchList": [],
    "cart":[]
}

###

DELETE http://localhost:8082/users/61fbe52dc123c92475c6bca5

###

PATCH http://localhost:8082/users/61fbe529c123c92475c6bca4
Content-Type: application/json

{
   
    "cart":{"product":""}
}

###